module.exports = [
    {
        name: 'Boneless Chicken breast',
        serving: 1 + 'oz',
        protein: 5.5 + 'g',
        calories: 28,
        carbohydrates: 0 + 'g',
        fats: .08 + 'g',
        id: 1
    },
    {
        name: 'Ground Beef 93/7', 
        serving: 1 + 'oz', 
        protein: 8.3 + 'g',
        calories: 59.3,
        carbohydrates: 0 + 'g',
        fats: 2.7 + 'g',
        id: 2,
    },
   
    {
        name: 'Ground Turkey 99%', 
        serving: 1 + 'oz', 
        protein: 7 + 'g',
        calories: 30,
        carbohydrates: 0 + 'g',
        fats: 0.3 + 'g',
        id: 3,
    },
   
    {
        name: 'Jasmine Rice', 
        serving: .25 + 'cup', 
        protein: 1 + 'g',
        calories: 51.25,
        carbohydrates: 11.25 + 'g',
        fats: .04 + 'g',
        id: 4,
    },
   
//     {
//         name: , 
//         serving: , 
//         protein: ,
//         calories: ,
//         carbohydrates: ,
//         fats: ,
//         id: 5,
//     },
   
//     {
//         name: , 
//         serving: , 
//         protein: ,
//         calories: ,
//         carbohydrates: ,
//         fats: ,
//         id: 6,
//     },
   
//     {
//         name: , 
//         serving: , 
//         protein: ,
//         calories: ,
//         carbohydrates: ,
//         fats: ,
//         id: 7,
//     },
   
//     {
//         name: , 
//         serving: , 
//         protein: ,
//         calories: ,
//         carbohydrates: ,
//         fats: ,
//         id: 8,
//     },
   
//     {
//         name: , 
//         serving: , 
//         protein: ,
//         calories: ,
//         carbohydrates: ,
//         fats: ,
//         id: 9,
//     },
   
//     {
//         name: , 
//         serving: , 
//         protein: ,
//         calories: ,
//         carbohydrates: ,
//         fats: ,
//         id: 10,
//     },
   
//     {
//         name: , 
//         serving: , 
//         protein: ,
//         calories: ,
//         carbohydrates: ,
//         fats: ,
//         id: 11,
//     },
   
//     {
//         name: , 
//         serving: , 
//         protein: ,
//         calories: ,
//         carbohydrates: ,
//         fats: ,
//         id: 12,
//     },
//     {
//         name: , 
//         serving: , 
//         protein: ,
//         calories: ,
//         carbohydrates: ,
//         fats: ,
//         id: 13,
//     },
//     {
//         name: , 
//         serving: , 
//         protein: ,
//         calories: ,
//         carbohydrates: ,
//         fats: ,
//         id: 14,
//     },
//     {
//         name: , 
//         serving: , 
//         protein: ,
//         calories: ,
//         carbohydrates: ,
//         fats: ,
//         id: 15,
//     },
//     {
//         name: , 
//         serving: , 
//         protein: ,
//         calories: ,
//         carbohydrates: ,
//         fats: ,
//         id: 16,
//     },
//     {
//         name: , 
//         serving: , 
//         protein: ,
//         calories: ,
//         carbohydrates: ,
//         fats: ,
//         id: 17,
//     },
//     {
//         name: , 
//         serving: , 
//         protein: ,
//         calories: ,
//         carbohydrates: ,
//         fats: ,
//         id: 18,
//     },
//     {
//         name: , 
//         serving: , 
//         protein: ,
//         calories: ,
//         carbohydrates: ,
//         fats: ,
//         id: 19,
//     },
//     {
//         name: , 
//         serving: , 
//         protein: ,
//         calories: ,
//         carbohydrates: ,
//         fats: ,
//         id: 20,
//     },
   

]